---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages/news
  label: News posts
  create: documents
  match: "**/*"
  templates:
  - news-post
- type: directory
  path: src/pages/blog
  label: Blog posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: uploads
public_path: "/src/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-preview
